spring:
datasource:
url: jdbc:postgresql://localhost:5432/intern_2
username: postgres
password: 1234
jpa:
database: postgresql
database-platform: org.hibernate.dialect.PostgreSQLDialect
generate-ddl: true
hibernate:
ddl-auto: update